fixtures:
  forge_modules:
    yumrepo_core: "puppetlabs-yumrepo_core"
    augeas_core: "puppetlabs-augeas_core"
    stdlib: "puppetlabs-stdlib"
    docker:
        repo: "puppetlabs/docker"
        ref: "3.10.2"
    cron_core: "puppetlabs-cron_core"
    translate: "puppetlabs-translate"
    puppet_authorization: "puppetlabs-puppet_authorization"
    service: "puppetlabs-service"
    facts: "puppetlabs-facts"
    puppet_agent: "puppetlabs-puppet_agent"
    hocon: "puppetlabs-hocon"
    ruby_task_helper: "puppetlabs-ruby_task_helper"
  repositories:
    puppet-enterprise-modules:
      repo: 'git@github.com:puppetlabs/puppet-enterprise-modules.git'
      ref: 'origin/kearney'
      target: 'spec/fixtures'
    pe_r10k:
        repo: "git@github.com:puppetlabs/puppetlabs-pe_r10k.git"
        ref: origin/2016.2.x
    enterprise_tasks:
        repo: "git@github.com:puppetlabs/enterprise_tasks.git"
        ref: origin/master
    pe_xl:
        repo: "git@github.com:reidmv/reidmv-pe_xl.git"
        ref: origin/main
    provision:
        repo: "git@github.com:puppetlabs/provision.git"
        ref: origin/master

  symlinks:
     puppet_enterprise: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/puppet_enterprise"
     pe_concat: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_concat"
     pe_postgresql: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_postgresql"
     pe_java_ks: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_java_ks"
     pe_inifile: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_inifile"
     pe_hocon: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_hocon"
     pe_puppet_authorization: "#{source_dir}/spec/fixtures/puppet-enterprise-modules/modules/pe_puppet_authorization"
     cd4pe: "#{source_dir}"
